"""Export the Koopman slide notebook to public/slides/koopman/ and inject site theme CSS."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parents[2]
NOTEBOOK = Path(__file__).resolve().parent / "koopman_population_states_slides.py"
OUT_DIR = SITE_ROOT / "public" / "slides" / "koopman"
OUT_HTML = OUT_DIR / "index.html"
INJECT_SCRIPT = SITE_ROOT / "scripts" / "inject_slides_theme.py"

# Prefer the sibling experiment venv (has marimo); fall back to PATH.
KOOPMAN_MARIMO = SITE_ROOT.parent / "KoopmanExperimentation" / ".venv" / "Scripts" / "marimo.exe"
KOOPMAN_MARIMO_UNIX = SITE_ROOT.parent / "KoopmanExperimentation" / ".venv" / "bin" / "marimo"


def _marimo_cmd() -> list[str]:
    if KOOPMAN_MARIMO.is_file():
        return [str(KOOPMAN_MARIMO)]
    if KOOPMAN_MARIMO_UNIX.is_file():
        return [str(KOOPMAN_MARIMO_UNIX)]
    return ["marimo"]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "figures").mkdir(parents=True, exist_ok=True)

    cmd = [
        *_marimo_cmd(),
        "export",
        "html",
        str(NOTEBOOK),
        "-o",
        str(OUT_HTML),
        "--no-include-code",
        "-f",
    ]
    print("Running:", " ".join(cmd))
    completed = subprocess.run(cmd, cwd=str(SITE_ROOT))
    if completed.returncode != 0:
        return completed.returncode

    inject = [
        sys.executable,
        str(INJECT_SCRIPT),
        str(OUT_HTML),
        "--talk",
        "koopman",
    ]
    print("Running:", " ".join(inject))
    inject_completed = subprocess.run(inject, cwd=str(SITE_ROOT))
    if inject_completed.returncode != 0:
        return inject_completed.returncode

    # Keep a small README next to the hosted artifact.
    readme = OUT_DIR / "README.md"
    readme.write_text(
        "# Koopman population-state slides\n\n"
        "Generated by `analysis/koopman-population-states/run.py`.\n"
        "Do not edit `index.html` by hand; re-export after notebook or figure changes.\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_HTML.relative_to(SITE_ROOT)}")
    print(f"Figures: {(OUT_DIR / 'figures').relative_to(SITE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
